name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  merge_group:
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Go From go.mod
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"
      - name: Run Unit Tests
        run: make test
